[package]
name = "conure_server"
version = "0.1.0"
edition = "2024"

[dependencies]
capnp = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
dotenv = "0.15.0"

[build-dependencies]
capnpc = { workspace = true }
