[package]
name = "conure_client"
version = "0.1.0"
edition = "2024"

[dependencies]
capnp = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }

[build-dependencies]
capnpc = { workspace = true }
